[package]
name = "guideofasync"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.1"
tokio = { version = "1.4.0", features = ["full"]}
log = "0.4"
env_logger = "0.9.0"
reqwest = "0.11.4"